### ISSUE TITLE
Bad state: Cannot write to socket, it is closed

### ISSUE THREAD

**Issue by Fraa-124** [adamlofts/mysql1_dart#114]
Hi there, I tried to follow the example but I keep getting this error.

Any suggestion? Mysql is successfully installed on my mac, I can connect thought the terminal.

And yes, the user, password and port are correct.

**Comment by ROBCON-Software** [comment]
provide Your code...

**Comment by Fraa-124** [comment]
Ok, I got it. after await connect() you have to wait some time. Otherwise any operation will fail because the db is not ready yet. It may be a bug or I'm doing it wrong

Thanks anyway, @ROBCON-Software
