### ISSUE TITLE
How to perform `transaction` query

### ISSUE THREAD

**Issue by idreesVenD** [adamlofts/mysql1_dart#123]
Please provide proper documentation for transaction query. I am having a hard time implementing one and I don't seem to find anything helpful regarding it. Even the internal package structure is unclear.

I am trying to run this query:

```dart
conn.transaction(() async {
  await conn.query("""INSERT INTO sonardb_local.projects (
      project_name,
      description
    )
    VALUES ( 
      "Test_2",
      "Testing CLI script the working of this thing"
    );""");
    
    await conn.query("SELECT @component_id := last_insert_id();");

    await conn.query("""
      INSERT INTO sonardb_local.project_platforms(
        display_name,
        component_id,
        project_id,
        platform_id
      )
      VALUES (
        "Test_2_Flutter",
        @component_id,
        @project_id,
        5
      );""");
});
```

My initial thought was that variable declaration is not supported so I tried running only:

```dart
  conn.transaction(() async {
    await conn.query("""INSERT INTO sonardb_local.projects (
        project_name,
        description
      )
      VALUES ( 
        "Test_2",
        "Testing CLI script the working of this thing"
      );""");
  });
```

and it is still not working.

Furthermore I have tried removing `async` and `await` that doesn't help either.

Can you please provide documentation on how to go by this.

Thank you.

**Comment by wustrong** [comment]
here is a example:  
     db.transaction((TransactionContext tx) async {
        // update with where
        var _ = await tx.query('update t_employee set dept_id = ? where id = 1', [3]);
        var result = await tx.query('select * from t_employee where id = 1');
      });
