### ISSUE TITLE
Please publish a new version to pub.dev

### ISSUE THREAD

**Issue by gmpassos** [adamlofts/mysql1_dart#133]
The current published version `mysql1 0.19.2` has some issues with null values and transactions. Since this is already fixed at GitHub, a new published version is very important.

Best Regards.

**Comment by gmpassos** [comment]
@adamlofts @rxlabz FYI

**Comment by gmpassos** [comment]
please!

**Comment by gmpassos** [comment]
Do you want any help to maintain this package?

Regards

**Comment by adamlofts** [comment]
I've published a new version.

There are a couple of big problems with this package, new mysql support and multiple statements in a query. Unfortunately I don't have time to work on them unfunded. Any help appreciated.

**Comment by gmpassos** [comment]
Thanks for the release! 🙏🏻

I can help with the package. I think that a TODO list (at README) will be helpful to drive the new changes and development.

Regards
