### ISSUE TITLE
MySQL Client Error: Authentication plugin not supported: caching_sha2_password

### ISSUE THREAD

**Issue by hyperpanthera** [adamlofts/mysql1_dart#15]
I am using MySQL 8.0.16!

```dart
Unhandled exception:
MySQL Client Error: Authentication plugin not supported: caching_sha2_password
#0      HandshakeHandler.processResponse (package:mysql1/src/auth/handshake_handler.dart:118:7)
#1      ReqRespConnection._handleData (package:mysql1/src/single_connection.dart:329:31)
<asynchronous suspension>
#2      ReqRespConnection._handleHeader (package:mysql1/src/single_connection.dart:298:13)
<asynchronous suspension>
#3      ReqRespConnection._readPacket (package:mysql1/src/single_connection.dart:283:7)
<asynchronous suspension>
#4      MySqlConnection.connect.<anonymous closure> (package:mysql1/src/single_connection.dart:120:13)
#5      BufferedSocket._onData (package:mysql1/src/buffered_socket.dart:93:11)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#10     _StreamController._add (dart:async/stream_controller.dart:640:7)
#11     _StreamController.add (dart:async/stream_controller.dart:586:5)
#12     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#13     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by YuanTianyang** [comment]
Your MysSQL is 8.0 or more. Your need to change this file which is named my.ini
Change the default_authentication_plugin to mysql_native_password。

**Comment by Notzuonotdied** [comment]
Hello, @adamlofts , do you plan to support this feature?

**Comment by adamlofts** [comment]
Pull requests adding this feature will be accepted.

Contact me by email for professional support.

**Comment by Katekko** [comment]
> m

Where are this file?

**Comment by Katekko** [comment]
For who are getting this error:

- executing the install file
- select "Reconfigure" over the mysql server
- In Authentication Method tab, select "Use Legacy Authentication Method"

ref: https://stackoverflow.com/questions/49931541/mysql-changing-authentication-type-from-standard-to-caching-sha2-password

**Comment by ahmed9378** [comment]
> For who are getting this error:
> 
> * executing the install file
> * select "Reconfigure" over the MySQL server
> * In Authentication Method tab, select "Use Legacy Authentication Method"
> 
> ref: https://stackoverflow.com/questions/49931541/mysql-changing-authentication-type-from-standard-to-caching-sha2-password

This one solved my problem. just for reference, the first step can be done through executing this software: "MySQL Installer - Community". you can find it using windows 10 search
