### ISSUE TITLE
Mysql1 dart package connection Error

### ISSUE THREAD

**Issue by bengalliboy** [adamlofts/mysql1_dart#28]
I have been getting this below error while I try to use mySQL1 package to directly talk to the database using flutter.

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 57351

Not sure why it is trying to use a different prot and not the one I am asking to use.....

Thanks!
Here is my code:

import 'package:mysql1/mysql1.dart'; void mySQLConnect () async{ final conn = await MySqlConnection.connect(new ConnectionSettings( host: 'localhost', port: 3306, user: 'xxxx', db: 'xxxx', password: xxxx' )); var results = await conn .query('select * from users'); for (var row in results) { print('UserName: ${row[0]}, Name: ${row[1]}'); } await conn.close(); }

**Comment by mingsai** [comment]
Check out the answers to this question about error 111 from mysql discussed on StackOVerflow (https://stackoverflow.com/questions/1420839/cant-connect-to-mysql-server-error-111). I've seen similar connection refused issues when using mysql and was able to solve them by adding a new user who has ability to connect from specific addresses to the db. I have been able to see the issue by running show processlist when attempting to connect and looking at the mysql logs during that time. This would show the users and ip addresses that are being connected to the db. Then just make a new user account with privileges to connect on a port that your mysqld is listening on.

**Comment by ankitsingh101** [comment]
Any Solution

**Comment by xxJeevesxx** [comment]
Are you using Android emulator? Try replacing the host with ‘10.0.2.2’. I had your exact problem and made this modification with great success!

**Comment by adamlofts** [comment]
See https://dev.mysql.com/doc/refman/8.0/en/problems-connecting.html for help.

**Comment by adamlofts** [comment]
The port in your error message likely refers to the local port not mysql one. The error says the OS cannot connect. Try connecting the mysql using a different tool.
