### ISSUE TITLE
Uncaught (in promise) Error: Unsupported operation: RawSocket constructor

### ISSUE THREAD

**Issue by ankitsingh101** [adamlofts/mysql1_dart#29]
`import 'package:flutter/material.dart';
import 'package:mysql1/mysql1.dart';

//void main() => runApp(new MyApp());

void main() async {
  final conn = await MySqlConnection.connect(new ConnectionSettings(
      host: 'localhost',
      port: xxxx,
      user: 'xxx',
      password: 'xxxx',
      db: 'xxxx'));
  var results = await conn.query('select * from xxxxxxx');
  for (var row in results) {
    print('Name: ${row[0]}');
  } 
}`

**Comment by SuperOzi01** [comment]
Did you solve this ?? because I have the same issue and I read it was Flutter 2 issue
