### ISSUE TITLE
Stored Procedure getting error

### ISSUE THREAD

**Issue by mjafartp** [adamlofts/mysql1_dart#3]
when calling a Stored Procedure it returning an error : " PROCEDURE dble.ItemGroupViewAll can't return a result set in the given context"

**Comment by adamlofts** [comment]
Can you provide a small test case to reproduce?

**Comment by kvacquier** [comment]
same here.

To reproduce
Store a procedure like this : 

DELIMITER ;;
CREATE DEFINER=`root`@`%` PROCEDURE `find_user_near`(min_lat DOUBLE, max_lat DOUBLE, min_long DOUBLE, max_long DOUBLE)
BEGIN
	SELECT users.userID FROM users
		WHERE
			users.`lat` BETWEEN min_lat AND max_lat
			AND users.`long` BETWEEN min_long AND max_long
		ORDER BY RAND()
		LIMIT 0, 50;
END;;
DELIMITER ;

(table with userID, lat and long of course) and call :  connection.query("find_user_near(0, 1000, 0, 1000)")

**Comment by adamlofts** [comment]
Did this fix your issue?
