### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by mnordine** [adamlofts/mysql1_dart#31]
Is there any way to pool connections?

**Comment by adamlofts** [comment]
Not built in. You can use https://pub.dev/packages/pool to implement a pool

**Comment by mnordine** [comment]
@adamlofts Doesn't that package just limit the # of pooled items?

**Comment by adammbox** [comment]
What functionality do you think it is missing?

**Comment by adamlofts** [comment]
What functionality do you think it is missing?

**Comment by mnordine** [comment]
Reuse of existing connections. I don't see how that works with `pool` package?
