### ISSUE TITLE
SocketException: Socket has been closed

### ISSUE THREAD

**Issue by MeloHenrique** [adamlofts/mysql1_dart#33]
Hi I am starting using flutter and this library.
Every time that I try to do something I get this error : 
 E/flutter (22925): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: Socket has been closed
E/flutter (22925): #0      MySqlConnection.connect (package:mysql1/src/single_connection.dart:142:5)
E/flutter (22925): <asynchronous suspension>
(and some more)

At this moment I am only trying to make a query.

This is my code:
Future confirmLogin() async {
  var settings = ConnectionSettings(
      host: '0.0.0.0',
      port: 3306,
      user: 'user',
      password: 'password',
      db: 'db'
  );
  final conn = await MySqlConnection.connect(settings);
  var user = await conn.query("SELECT * FROM `something` WHERE some = 'something'");
  debugPrint("Valor é: $user");
  await conn.close();
}

I do not think that the problem is with my user and password.

**Comment by MeloHenrique** [comment]
The problem was with the acess host.

**Comment by emre13k** [comment]
@MeloHenrique how do you fix this problem?
