### ISSUE TITLE
dart(ambiguous_import)

### ISSUE THREAD

**Issue by divyanshuk10** [adamlofts/mysql1_dart#4]
The name 'Row' is defined in the libraries 'package:flutter/src/widgets/basic.dart' and 'package:mysql1/src/results/row.dart'.dart(ambiguous_import)

![screen shot 2018-12-18 at 11 42 50 am](https://user-images.githubusercontent.com/19980597/50135421-21750300-02ba-11e9-9857-18b541e6b779.png)

is there any solution for this ambiguity error.
my imports are as follow:-

import 'package:flutter/material.dart';
import 'package:mysql1/mysql1.dart' ;

**Comment by adamlofts** [comment]
You can use an import like `import 'package:mysql1/mysql1.dart show MySqlConnection` to import only some identifiers from a package.

**Comment by divyanshuk10** [comment]
Can we use this in Mobile client code base for iOS and android. 
Will this violate the Apple Store submission guidelines?

**Comment by adamlofts** [comment]
What are your specific concerns?

**Comment by divyanshuk10** [comment]
> You can use an import like `import 'package:mysql1/mysql1.dart show MySqlConnection` to import only some identifiers from a package.

okay thanks for your reply..!
