### ISSUE TITLE
What is the equivalent of real_escape_string (from php) in this driver?

### ISSUE THREAD

**Issue by mhbdev** [adamlofts/mysql1_dart#43]
I am looking for an equivalent for real_escape_string in this package? is there any?

**Comment by mhbdev** [comment]
> I am looking for an equivalent for real_escape_string in this package? is there any?

What can we do to avoid sql injections?

**Comment by adamlofts** [comment]
You should use parameterised queries as shown in the docs:

https://pub.dev/documentation/mysql1/latest/mysql1/MySqlConnection/query.html
