### ISSUE TITLE
Error 1130 connection error

### ISSUE THREAD

**Issue by AhmedEzio47** [adamlofts/mysql1_dart#44]
Error 1130 (ost '): 192.168.1.5' is not allowed to connect to this MariaDB server, this error occurs when I try to connect to MySQL Database on my computer, what does this mean?, I changed localhost to my computer IP.

**Comment by adamlofts** [comment]
This is not a driver issue. 

See https://dev.mysql.com/doc/refman/8.0/en/problems-connecting.html for help.
