### ISSUE TITLE
The method 'query' isn't defined for the class 'Future<MySqlConnection>'.

### ISSUE THREAD

**Issue by gissow87** [adamlofts/mysql1_dart#50]
i am trying to run an example but i cant get it right

I leave my code below:

import 'package:mysql1/mysql1.dart';
import 'dart:async';

Future<MySqlConnection> conexionDB() async{
  var settings = new ConnectionSettings(
      host: '10.0.2.2',
      port: 3306,
      user: 'root',
      password: '',
      db: 'NearMarketDB'
  );
  var conn = await MySqlConnection.connect(settings);
  return conn;
}

void registrarUsuario(String nombre, String dni, String telefono, String email, String contrasenia, String direccion, String provincia, String codigoPostal, String fechaNacimiento) async{
  dynamic conn = conexionDB();
  var result = await conn.query('insert into nm_usuarios (nombre, dni, telefono, email, contrasenia, direccion, provincia, codigoPostal, fechaNacimiento) '
      'values (?, ?, ?)', [nombre, dni, telefono, email, contrasenia, direccion, provincia, codigoPostal, fechaNacimiento]);
}

Here is the error message:
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: Class 'Future<MySqlConnection>' has no instance method 'query'.

**Comment by adamlofts** [comment]
`dynamic conn = conexionDB();` should be `dynamic conn = await conexionDB();`
