### ISSUE TITLE
How to retrieve field name from query ?

### ISSUE THREAD

**Issue by Rockvole** [adamlofts/mysql1_dart#6]
Hi,
Thank-you for your work on this library.

I am trying to retrieve the field name returned from the query method, but having no luck.
e.g.

    _conn.query(sql).then((Results results) {
      for(Row row in results) {
        int i=0;
        print("Row="+row.toString());
        row.forEach((v) {
          print("value="+v.toString());
        });
      }
    });

I would like to retrieve <i>item_description</i> & <i>item_complete</i> from here :

    SELECT              item_description,             item_complete     FROM task_item WHERE task_id = 1
    Row=Fields: {item_description: Walk to shops, item_complete: 1}
    value=Walk to shops
    value=1

And <i>Tables_in_sharecal (task_item)</i> from here :

    SHOW TABLES LIKE 'task_item'
    Row=Fields: {Tables_in_sharecal (task_item): task_item}
    value=task_item

I tried various methods (such as map / asMap) but they didnt return the keys / field names.

**Comment by adamlofts** [comment]
You should be able to use ```results.fields``` documented here: https://pub.dartlang.org/documentation/mysql1/latest/mysql1/Results/fields.html
