### ISSUE TITLE
Not able to use Row() widget

### ISSUE THREAD

**Issue by kunalsaraf** [adamlofts/mysql1_dart#7]
When I import 'package:mysql1/mysql1.dart' package, I am unable to use Row. It says Row is defined in 'package:flutter/src/widgets/basic.dart' as well as 'package:mysql1/mysql1.dart'.
So I have to import the former package explicitly.

**Comment by adamlofts** [comment]
Yeah, this is a known issue. Probably Row should be renamed to something else.

**Comment by adamlofts** [comment]
Duplicate of #10
